name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: echo "Action works!"

      - uses: actions/checkout@v4

      - name: Install and Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_PROJECT_ID: prj_RQ85uJSKoCUpIjeAm9YpdAtEVypN
        run: |
          npm install -g vercel@latest
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          vercel build --prod --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
